# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  financingpms:
    image: financingpms
    build:
      context: .
      dockerfile: FinancingPMS/Dockerfile
    ports:
      - 5000
